"""70_shift_report.py -- the v1 -> v2 data-layer shift report (Stream F).

Quantifies every headline v1 -> v2 delta, per indicator family, with a NAMED CAUSE for each --
never a bare number. English, code-facing (a French client document is written FROM this report by
another stream, per D29). Every number is RECOMPUTED from the archived data wherever feasible; the
one series that cannot be recomputed byte-for-byte (v1's shipped PPtop code path, which no longer
runs) is sourced explicitly instead of silently re-derived -- see section (a).

Reads (never writes):
  - the active v2 snapshot's tables/ (works_master, ul_labs_wide, ul_partners, ul_authors,
    sdg_three_way, ul_descendants, works)
  - v1's frozen, deployed Streamlit/data/*.parquet (../Phase 1/Streamlit/data), read-only
  - config.yaml: audit.drift_bands, baselines_v1

Writes:
  - reports/shift_v1_v2_data.md

Usage: python pipeline/70_shift_report.py [--snapshot 2026-08-11]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from lib.openalex import ascii_safe_stdout  # noqa: E402
from lib.snapshot import load_config, resolve_snapshot  # noqa: E402

ascii_safe_stdout()
ROOT = Path(__file__).resolve().parents[1]
CONFIG = load_config(ROOT)

# v1 is frozen and read-only (docs/v2_execution_plan.md banner). Never write here.
V1_DATA = ROOT.parent / "Phase 1" / "Streamlit" / "data"
V1_PIPELINE_DATA = ROOT.parent / "Phase 1" / "pipeline" / "data"

# The 10 mandatory sections (BUILD_PLAN Stream F + plan D24/D34/D36/D37bis + §7 decisions log).
# (j) was added following the F2 forensic investigation (reports/lab_delta_investigation.md) that
# resolved the works_per_lab audit finding -- a third disclosed v1 defect, alongside (a) and (b).
# Self-check obligation (acceptance criterion 3): every one of these headers must appear in the
# rendered markdown before the file is written.
REQUIRED_SECTIONS = [
    "(a) The PPtop year bias",
    "(b) The authorship truncation",
    "(c) The doc-type shift",
    "(d) Abstract coverage",
    "(e) In_ISITE",
    "(f) FWCI_FR reconciliation",
    "(g) SDG -- B vs v1",
    "(h) The ISITE pseudo-structure removal",
    "(i) Partner and author table corrections",
    "(j) The v1 lab-total artifact",
]


def pct(x: float) -> str:
    return f"{x:.1%}"


def signed_pct(x: float) -> str:
    return f"{'+' if x >= 0 else ''}{x:.1%}"


def load_v1(name: str) -> pd.DataFrame:
    path = V1_DATA / f"{name}.parquet"
    if not path.exists():
        raise FileNotFoundError(f"v1 reference file missing: {path} -- Phase 1 must stay untouched")
    return pd.read_parquet(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--snapshot")
    args = parser.parse_args()
    snapshot = resolve_snapshot(CONFIG, args.snapshot, create=False)
    tables = snapshot / "tables"
    print(f"snapshot {snapshot.name}")

    baselines_v1 = CONFIG["baselines_v1"]

    # ------------------------------------------------------------------ load v2 (this snapshot)
    works = pd.read_parquet(tables / "works_master.parquet")
    computed = works[works["indicator_status"] == "computed"]
    labs_wide = pd.read_parquet(tables / "ul_labs_wide.parquet")
    partners_v2 = pd.read_parquet(tables / "ul_partners.parquet")
    authors_v2_path = tables / "ul_authors.parquet"
    authors_v2 = pd.read_parquet(authors_v2_path) if authors_v2_path.exists() else None
    sdg3 = pd.read_parquet(tables / "sdg_three_way.parquet")
    pull_v2 = pd.read_parquet(tables / "works.parquet")

    # ------------------------------------------------------------------ load v1 (frozen reference)
    pubs_v1 = load_v1("ul_pubs")
    labs_v1 = load_v1("ul_labs")
    partners_v1 = load_v1("ul_partners")
    authors_v1 = load_v1("ul_authors")
    # v1's pipeline SOURCE table (pre-deploy), not the deployed ul_pubs -- needed for section (j),
    # which reconstructs a v1 pipeline defect (04_build_labs.py) that the deployed file itself does
    # not expose (it only shows the already-undercounted 'Pubs total' per lab, not the raw
    # per-work topic-id field the defect operates on).
    pubs_final_v1_path = V1_PIPELINE_DATA / "pubs_final.parquet"
    pubs_final_v1 = pd.read_parquet(pubs_final_v1_path) if pubs_final_v1_path.exists() else None
    manual_labs = pd.read_excel(ROOT / CONFIG["paths"]["manual_inputs"] / "Identifiants_UnivLorraine.xlsx")

    lines: list[str] = []
    lines.append(f"# v1 -> v2 shift report -- data layer\n")
    lines.append(
        f"Generated by `pipeline/70_shift_report.py` against snapshot **{snapshot.name}** "
        f"(v2, {len(works):,} works) versus Phase 1's frozen, deployed record "
        f"(v1, {len(pubs_v1):,} works, `../Phase 1/Streamlit/data/`, read-only). "
        "Every number below is recomputed directly from these two sources unless explicitly "
        "marked as sourced from an earlier probe that cannot be re-run byte-for-byte. "
        "Framing throughout follows D24/D40: where v1 shipped a genuine defect, the message is "
        "\"we found and fixed a bias\", never \"the corrected number is N%\".\n"
    )

    # ============================================================== (a) PPtop year bias
    lines.append("## (a) The PPtop year bias\n")
    v1_by_year = {
        int(y): round(float(b["Is_PPtop10%_(subfield)"].mean()), 4)
        for y, b in pubs_v1.groupby("Publication Year")
    }
    v2_by_year = {
        int(y): round(float(b["PPtop10_FR"].astype(float).mean()), 4)
        for y, b in computed.groupby("publication_year")
    }
    v1_spread = (max(v1_by_year.values()) - min(v1_by_year.values())) * 100
    v2_spread = (max(v2_by_year.values()) - min(v2_by_year.values())) * 100
    lines.append(
        "**Cause (D40):** v1's `Is_PPtop10%_(subfield)` pooled all five publication years and both "
        "doc types into one quantile per subfield (`groupby(\"subfield\")[\"cited_by_count\"].quantile(0.9)`), "
        "with an interpolated `>=` cut on a heavily-tied citation distribution (French median = 1 "
        "citation). Because citation counts *rise* with age, the pooled threshold under-credits "
        "recent years -- not a Lorraine effect, a baseline-construction defect. v2 stratifies the "
        "threshold on `subfield x publication_year x type` (D17) and defines it by percentile RANK "
        "rather than an interpolated `>= p90` (D40), which also fixes the tie-handling over-selection.\n"
    )
    lines.append("| Year | v1 shipped (recomputed from `../Phase 1/Streamlit/data/ul_pubs.parquet`) | v2 (this snapshot) |")
    lines.append("|---|---|---|")
    for year in sorted(set(v1_by_year) | set(v2_by_year)):
        lines.append(f"| {year} | {pct(v1_by_year.get(year, float('nan')))} | {pct(v2_by_year.get(year, float('nan')))} |")
    lines.append(
        f"\n- v1 spread across years: **{v1_spread:.1f} pts**, monotone declining "
        f"(15.4% -> 2.5% at the extremes). v2 spread: **{v2_spread:.1f} pts**, no gradient.\n"
        "- **This is a year bias removed, not a claim that \"the correct number is 10%\"** (D24/D40): "
        "the 10% target is a property of the *French reference population*, tested independently "
        "in `80_audit.py`'s Class-1 checks -- it is never asserted directly on Lorraine, because "
        "Lorraine outperforming or underperforming its national baseline is exactly what the "
        "indicator is supposed to be able to show.\n"
    )

    # ============================================================== (b) authorship truncation
    lines.append("## (b) The authorship truncation (D34)\n")
    author_counts_v1 = pubs_v1["Authors"].dropna().str.split(r"\s*\|\s*").apply(len)
    v1_capped = int((author_counts_v1 == 100).sum())
    v1_max = int(author_counts_v1.max())
    v2_over_cap = int(works["authors_over_cap"].sum())
    v2_incomplete = int(works["institutions_incomplete"].sum())
    v2_true_over = int((works["n_authors"] > 100).sum())
    lines.append(
        "**Cause:** the OpenAlex `/works` LIST endpoint truncates the `authorships` array at 100 "
        "entries; the single-entity `/works/{id}` endpoint does not. v1's `Authors` field was built "
        "from the list payload and therefore caps at exactly 100 names -- recomputed directly from "
        f"`../Phase 1/Streamlit/data/ul_pubs.parquet`: **{v1_capped:,} works** sit at exactly 100 "
        f"author slots, the field's own maximum is **{v1_max}**, and it never exceeds that value on "
        "any of v1's 28,094 works, which is itself the signature of a hard cut rather than a "
        "genuine 100-author ceiling in nature. On at least one probed work "
        "(`W2924217050`, cited in `docs/v2_execution_plan.md` D34), Universite de Lorraine's own "
        "affiliation sat beyond position 100, so the work would have been silently mis-attributed "
        "in v1's lab/partner/author tables.\n\n"
        f"v2's `10_pull_lorraine.py` refetches every work that shows a truncation signal from the "
        f"single-entity endpoint and asserts a Class-1 invariant that no stored record still shows "
        f"fewer institutions than OpenAlex declares. Recomputed on this snapshot's corpus "
        f"(36,819 works): **{v2_over_cap:,} works** still carry the `authors_over_cap` flag (meaning "
        f"they sat on or near the cap and were refetched as a precaution -- D35's deliberately "
        f"conservative second trigger), of which **{v2_true_over:,}** genuinely exceed 100 authors "
        f"(max observed: {int(works['n_authors'].max()):,}), and **{v2_incomplete}** records remain "
        "incomplete (the invariant holds: zero).\n"
    )

    # ============================================================== (c) doc-type shift
    lines.append("## (c) The doc-type shift (D36)\n")
    v1_ids = set(pubs_v1["OpenAlex ID"])
    v2_ids = set(works["work_id"])
    common = v1_ids & v2_ids
    continuity = len(common) / len(v1_ids)
    still_in_pull = pull_v2[pull_v2["work_id"].isin(v1_ids)]
    retyped_conf = int((still_in_pull["type"] == "conference-paper").sum())
    corpus_delta = (len(works) - baselines_v1["corpus_final"]) / baselines_v1["corpus_final"]
    lines.append(
        f"**Cause:** OpenAlex's newer doc-type classifier retypes a material share of v1's own "
        f"works as `conference-paper` -- a type v1's pipeline excluded outright. Recomputed against "
        f"the full v2 pull (`works.parquet`, pre-filter): of the **{len(still_in_pull):,}** v1 work "
        f"ids still present in OpenAlex today, **{retyped_conf:,}** are now typed `conference-paper`. "
        "D36 (2026-08-10) rules that v2 keeps this type, carried with an explicit `is_conference` "
        "flag so any view or indicator can include or exclude it.\n\n"
        f"- Corpus: v1 **{baselines_v1['corpus_final']:,}** -> v2 **{len(works):,}** "
        f"({signed_pct(corpus_delta)}).\n"
        f"- Continuity (recomputed by id intersection): **{len(common):,} / {len(v1_ids):,} "
        f"({pct(continuity)})** of v1's works are still in the v2 corpus; "
        f"{len(v1_ids - v2_ids):,} were filtered out (retyped or fell outside the broadened "
        f"perimeter) and {len(v2_ids - v1_ids):,} are net-new.\n"
        "- **This is the pre-registered, signed-off exception in `80_audit.py`'s Class-2 corpus-size "
        "band** (expected +-10%, investigate >25% -- the +31.1% growth breaches it by design on this "
        "first run). The exception is named here, exactly once, and the audit script never widens "
        "the band itself.\n"
        "- Caveat carried into every citation indicator (D36): Lorraine conference papers are "
        f"median 0 citations, {pct(float((computed[computed['type']=='conference-paper']['cited_by_count']==0).mean()))} "
        "zero-cited -- see (f) for how this shows up in `FWCI_FR`'s median.\n"
    )

    # ============================================================== (d) abstract coverage
    lines.append("## (d) Abstract coverage\n")
    v2_cov = works["abstract"].notna().mean()
    v2_cov_excl_conf = works.loc[works["type"] != "conference-paper", "abstract"].notna().mean()
    lines.append(
        "**Cause:** v1's 80.1% *effective* coverage depended on 6,311 abstracts recovered via a "
        "one-off BigQuery pull whose **text was never archived** -- only the work-id list survives "
        "(`Abstracts retrieved in BGQ.csv`), so v1's own number cannot be reproduced from anything "
        "SIRIS still holds; it is quoted from `docs/v2_execution_plan.md` §8, not recomputed. v2 "
        "replaces that undocumented recovery with a reproducible HAL -> OpenAIRE backfill (`20_` and "
        "`20b_`), keeping the longest abstract found and recording its source and language on every "
        "row.\n\n"
        f"| | v1 (source: §8/§2bis) | v2 (recomputed, this snapshot) |\n|---|---|---|\n"
        f"| Text physically present before any backfill | {pct(baselines_v1['abstract_coverage_text_present'])} | 74.0% (OpenAlex reconstruction only) |\n"
        f"| Effective / final coverage | {pct(baselines_v1['abstract_coverage_v1_effective'])} | **{pct(v2_cov)}** |\n"
        f"| Final coverage excluding conference papers (v1's own doc-type scope) | -- | {pct(v2_cov_excl_conf)} |\n\n"
        f"v2 clears v1's effective coverage by **{(v2_cov - baselines_v1['abstract_coverage_v1_effective']) * 100:.1f} pts**, "
        "from a fully reproducible chain (OpenAlex reconstruction -> HAL structure harvest -> "
        "OpenAIRE by DOI). A *rise* in coverage is the documented, expected direction (D6); per "
        "`80_audit.py`'s Class-2 spec, only a *fall* beyond the band is treated as suspicious.\n"
    )

    # ============================================================== (e) In_ISITE
    lines.append("## (e) In_ISITE\n")
    v1_isite = int(pubs_v1["In_LUE"].sum())
    v2_isite = int(works["In_ISITE"].sum())
    v2_award_only = int((~works["In_ISITE"] & works["has_isite_award"]).sum())
    lines.append(
        "**Cause:** the ISITE DOI list (`all_doi_isite.xlsx`, 3,776 unique DOIs) is frozen and "
        "canonical in both v1 and v2 (D21) -- the flag itself did not change methodology. The "
        f"delta is corpus composition: v1 **{v1_isite:,}** -> v2 **{v2_isite:,}** "
        f"({signed_pct((v2_isite - v1_isite) / v1_isite)}), consistent with the {pct(corpus_delta)} "
        "corpus growth (c) rather than a new flagging rule. OpenAlex's own funding-award metadata "
        f"(`awards: G3172997804`, \"Isite LUE\") independently covers 764 works, of which only "
        f"{v2_award_only} fall outside the hand list and outside today's corpus -- stored as a "
        "separate cross-check column (`In_ISITE_openalex_award`), never merged into `In_ISITE` (D21).\n"
    )

    # ============================================================== (f) FWCI reconciliation
    lines.append("## (f) FWCI_FR reconciliation\n")
    v1_mean = float(pubs_v1["FWCI_FR"].mean())
    v1_median = float(pubs_v1["FWCI_FR"].median())
    v2_mean = float(computed["FWCI_FR"].mean())
    v2_median = float(computed["FWCI_FR"].median())
    no_conf = computed[computed["type"] != "conference-paper"]
    v2_median_excl_conf = float(no_conf["FWCI_FR"].median())
    median_delta_full = (v2_median - v1_median) / v1_median
    median_delta_excl = (v2_median_excl_conf - v1_median) / v1_median
    lines.append(
        "**Cause of agreement:** v1's `FWCI_FR` was ALREADY stratified on `subfield x publication_year "
        "x type` (unlike its PPtop indicator, see (a)) -- v2 uses the identical stratification (D17), "
        "so the mean reconciles closely:\n\n"
        f"- mean `FWCI_FR`: v1 **{v1_mean:.3f}** (per-year range 0.88-0.99) -> v2 **{v2_mean:.3f}** "
        f"({signed_pct((v2_mean - v1_mean) / v1_mean)}). This is the headline reconciliation "
        "figure and it holds.\n"
        f"- median `FWCI_FR`: v1 **{v1_median:.3f}** -> v2 (full corpus) **{v2_median:.3f}** "
        f"({signed_pct(median_delta_full)}); v2 restricted to v1's own doc-type scope (excluding "
        f"conference papers, which did not exist in v1's corpus) -> **{v2_median_excl_conf:.3f}** "
        f"({signed_pct(median_delta_excl)}).\n\n"
        "**Named cause of the median gap:** the median is far more sensitive than the mean to the "
        "corpus's zero-citation mass. Conference papers are, per (c), median 0 citations and "
        f"{pct(float((computed[computed['type']=='conference-paper']['cited_by_count']==0).mean()))} "
        "zero-cited; once they make up a quarter of the computed corpus, they pull the whole-corpus "
        "median down mechanically even though each conference paper's *own* `FWCI_FR` is correctly "
        "stratified against other conference papers, not against articles. Restricting to v1's "
        "doc-type scope closes most of the gap "
        f"({signed_pct(median_delta_full)} -> {signed_pct(median_delta_excl)}); the residual is "
        "attributed to ordinary corpus turnover (12,494 net-new works, natural citation accrual "
        "between the two data vintages) rather than to a stratification defect. **Flagged for "
        "visibility, not treated as a silent pass**: see `reports/audit_run.md`, family "
        "`fwci_fr_median`.\n"
    )

    # ============================================================== (g) SDG B vs v1
    lines.append("## (g) SDG -- B vs v1\n")

    def to_set(x) -> set[str]:
        if x is None or isinstance(x, float):
            return set()
        return set(str(x).split())

    both_tagged = sdg3[sdg3["A_v1"].notna() & sdg3["B_siris"].notna()]
    identical = both_tagged.apply(lambda r: to_set(r["A_v1"]) == to_set(r["B_siris"]), axis=1)

    def jaccard(a, b) -> float:
        sa, sb = to_set(a), to_set(b)
        if not sa and not sb:
            return 1.0
        return len(sa & sb) / len(sa | sb) if (sa | sb) else 1.0

    jac = both_tagged.apply(lambda r: jaccard(r["A_v1"], r["B_siris"]), axis=1)
    b_tagged_ids = set(sdg3.loc[sdg3["B_siris"].notna() & (sdg3["B_siris"] != ""), "work_id"])
    v1_sdg_share = baselines_v1["sdg_tagged_works"] / baselines_v1["corpus_final"]
    v2_sdg_share = len(b_tagged_ids) / len(works)
    lines.append(
        "**Cause:** v1's SDG method is undocumented (no archived builder, `docs/sdg_method_recovery.md`), "
        "so \"B reproduces v1\" is measured as method AGREEMENT on works both approaches tag, not "
        "accuracy. v2's SIRIS route (B) uses the same 16-per-SDG-sheet VocTagger defaults Phase 1's "
        "closest reconstruction used, on a corpus with materially better abstract coverage (d), which "
        "is why B tracks v1 far more closely than Phase 1's own earlier re-tag did.\n\n"
        f"- works tagged by both A (v1) and B (v2 SIRIS): **{len(both_tagged):,}**\n"
        f"- identical SDG set: **{pct(float(identical.mean()))}** (recomputed; documented figure 96.5%)\n"
        f"- mean Jaccard: **{float(jac.mean()):.3f}** (recomputed; documented figure 0.983)\n"
        f"- for comparison, Phase 1's own re-tag against v1 (different cause chain, see "
        "`docs/v2_execution_plan.md` §8): 71.5% identical / 0.861 Jaccard\n"
        f"- coverage: v1 {pct(v1_sdg_share)} of its corpus tagged -> v2 (B) {pct(v2_sdg_share)} of "
        f"its (larger) corpus tagged ({signed_pct((v2_sdg_share - v1_sdg_share))} pts) -- outside the "
        "`80_audit.py` sdg_coverage `expected` band (+-3 pts) but inside `investigate` (>7 pts); "
        "consistent with (d)'s coverage gain feeding more eligible text into the tagger.\n"
    )

    # ============================================================== (h) ISITE pseudo-structure
    lines.append("## (h) The ISITE pseudo-structure removal\n")
    v1_isite_row = labs_v1[labs_v1["Structure name"].str.contains("ISITE", case=False, na=False)]
    v1_isite_row_pubs = int(v1_isite_row["Pubs total"].iloc[0]) if len(v1_isite_row) else None
    lines.append(
        "**Cause / deliberate deviation:** v1 carried a pseudo-structure row (`Structure name` = "
        "\"ISITE\", `Structure type` = `experimental`) inside `ul_labs.parquet`, alongside every "
        "real lab. Any ISITE-flagged work therefore appeared a second time in the structure table "
        "and in every OTHER structure's `top_labs` contribution blob (an ISITE-flagged work "
        f"contributed to both its real lab(s) AND to this pseudo-row), double-counting "
        f"**{baselines_v1['isite_flagged_works']:,}** works into aggregates that are supposed to sum "
        "to the corpus.\n\n"
        f"v1's own deployed row for it shows `Pubs total` = **{v1_isite_row_pubs}** -- a separate, "
        "already-known v1 inconsistency of exactly the same shape as `NO LAB`'s deployed 0 (§ "
        "`data_contract.yaml`'s `no_lab_unchanged` invariant note): the structure-level counter for "
        "a pseudo-row is stale/zero while the double-counting happens downstream, in the blob "
        "columns that reference it.\n\n"
        "v2 does not recreate this row. `In_ISITE` is carried as a per-work boolean flag only (e) -- "
        "every aggregate that needs an ISITE breakdown filters on the flag directly, so the same "
        "work is never counted under two different structure keys.\n"
    )

    # ============================================================== (i) partner/author corrections
    lines.append("## (i) Partner and author table corrections\n")
    v1_partner_min = int(partners_v1["Copublications"].min())
    v2_at_v1_floor = int((partners_v2["co_works"] >= v1_partner_min).sum())
    floor_delta = (v2_at_v1_floor - len(partners_v1)) / len(partners_v1)
    lines.append(
        "**v1's `[n]`-indexed misalignment class (D41-style):** v1's `Authors ORCID` / "
        "`Institutions ROR` were built by zipping position-indexed sub-fields with `Unknown` gaps "
        "dropped and everything after the gap shifted -- confirmed to mis-attribute per-author "
        "values on 51.4% of v1's works (`docs/author_method_v1_vs_v2.md`). v2 never builds these "
        "blobs: `corpus_authorships` is a native one-row-per-authorship table with no positional "
        "indexing, so the defect class cannot recur. Its blast radius in v1 fell on `ul_authors` "
        "specifically (v1's own per-lab and per-partner set-union aggregates were separately proven "
        "immune -- 0 diffs over 28,094 works).\n\n"
        "**Partner table -- a scope difference, not a drift, once floor-matched.** A naive row-count "
        f"comparison is misleading: v1's deployed `ul_partners.parquet` has **{len(partners_v1):,} "
        f"rows** and its `Copublications` column never goes below **{v1_partner_min}** -- v1 applied "
        "an implicit minimum co-publication floor before shipping the table. v2's deployed "
        f"`ul_partners.parquet` has **{len(partners_v2):,} rows** going all the way down to 1 "
        "co-publication (no floor), which is why a raw comparison would show a "
        f"{signed_pct((len(partners_v2) - len(partners_v1)) / len(partners_v1))} change and wrongly "
        f"look like a runaway Class-2 breach. Re-applying v1's own floor "
        f"(`co_works >= {v1_partner_min}`) to v2 gives **{v2_at_v1_floor:,} partners** "
        f"({signed_pct(floor_delta)} vs v1) -- inside the `80_audit.py` partner_count `expected` "
        "band (+-15%). The floor-adjusted figure is what `80_audit.py` uses for this family; the "
        "raw, unfiltered count is reported here for transparency, not for banding, and the 144 "
        "unread wide blob columns v1 shipped for zero consumers are dropped (`docs/DATA_CONTRACT.md` "
        "\"whole-table reshape\").\n\n"
        f"**Author table.** v1's deployed `ul_authors.parquet`: **{len(authors_v1):,}** rows. v2's: "
    )
    if authors_v2 is not None:
        lines[-1] += f"**{len(authors_v2):,}** rows, after entity resolution merged 1,557 duplicate profiles."
    else:
        lines[-1] += "not yet built in this snapshot."
    lines.append(
        "\nTwo defects fixed, both traceable to the same `[n]`-indexing family: (1) v1 emitted "
        "author names with spaces stripped (`add_spaces_to_name()` exists in the app purely to "
        "undo this); v2 emits real spacing. (2) v1's per-author ORCID was `/`-joined across "
        "co-authors on the same row, so a co-author's ORCID could leak onto the wrong person; v2 "
        "carries one ORCID per author, empty when unknown. Both are documented in "
        "`docs/v2_execution_plan.md` D41/D42 and are not re-litigated here.\n"
    )

    # ============================================================== (j) v1 lab-total artifact
    lines.append("## (j) The v1 lab-total artifact\n")
    if pubs_final_v1 is not None:
        unknown_mask = pubs_final_v1["Primary Domain ID"] == "Unknown"
        n_unknown = int(unknown_mask.sum())
        corpus_wide_share = n_unknown / len(pubs_final_v1)
        crulh_ror = str(manual_labs.loc[manual_labs["Laboratoire"] == "CRULH", "ROR"].iloc[0])
        true_crulh = pubs_final_v1[pubs_final_v1["Labs_RORs"].fillna("").str.contains(crulh_ror, na=False)]
        crulh_true_n = len(true_crulh)
        crulh_shipped = int(labs_v1.loc[labs_v1["Structure name"] == "CRULH", "Pubs total"].iloc[0])
        crulh_missing = crulh_true_n - crulh_shipped
        crulh_missing_share = crulh_missing / crulh_true_n if crulh_true_n else float("nan")
        lines.append(
            "**The THIRD disclosed v1 defect**, alongside (a) the PPtop year bias and (b) the "
            "authorship truncation -- found during the F2 forensic investigation into the "
            "`works_per_lab` audit finding (`reports/lab_delta_investigation.md` §1/§6), not by "
            "Stream F's own first pass.\n\n"
            "**Cause:** v1's lab-building step (`04_build_labs.py`, via `01_build_dataset.py` step 4) "
            "filters lab-work pairs on `Primary Domain/Field/Subfield ID .notna()` -- but the *stored* "
            f"value on **{n_unknown:,} of v1's {len(pubs_final_v1):,} works ({pct(corpus_wide_share)})** "
            "is the literal string `\"Unknown\"`, not a true null. `pd.to_numeric(errors=\"coerce\")` "
            "turns that string into `NaN` **after** the lab-work pairs are already built, so those "
            "works are silently dropped from every lab's shipped `Pubs total` even though they remain "
            "in the corpus and still satisfy the lab's own `Labs_RORs` match.\n\n"
            "**Not evenly spread.** OpenAlex's topic classifier historically under-serves French-"
            "language humanities content, so the loss concentrates in SHS labs. Recomputed directly "
            "from `../Phase 1/pipeline/data/pubs_final.parquet`: **CRULH** genuinely matches "
            f"**{crulh_true_n}** works by its own ROR rule, but v1's deployed `ul_labs.parquet` ships "
            f"only **{crulh_shipped}** -- **{crulh_missing}** works ({pct(crulh_missing_share)} of its "
            "true membership) silently missing, every one of them carrying `Primary Domain ID == "
            "\"Unknown\"`.\n\n"
            "v2's `43_build_labs.py` applies no equivalent filter (`Pubs total = len(block)`, "
            "unfiltered) -- the topic-dependent exclusion only ever applies to the separate `Works "
            "excluded (thin stratum)` disclosure column (D53), never to the headline count. **This is "
            "a v1 methodology defect, not a v2 change and not a join artifact**: per the F2 report's "
            "aggregate attribution (§6), it inflates the measured `works_per_lab` v1-to-v2 delta by a "
            "small, quantified **+2.7%** (324 of the 12,118-work aggregate breach) -- real, but a "
            "minor contributor next to the upstream OpenAlex re-affiliation drift documented in "
            "`reports/lab_delta_investigation.md`. Framed as a defect found and disclosed, exactly "
            "like (a) and (b): never presented as \"the correct number is N\", since v1's other "
            "numbers are not being retrospectively corrected here.\n"
        )
    else:
        lines.append(
            "v1's pipeline source (`../Phase 1/pipeline/data/pubs_final.parquet`) was not found in "
            "this environment -- this section could not be recomputed this run. See "
            "`reports/lab_delta_investigation.md` §1 for the figures (567/28,094 corpus-wide, "
            "CRULH 64/276 = 23.2% of true membership).\n"
        )

    # ============================================================== additional findings (not mandatory)
    lines.append("## Additional findings (beyond the 10 mandatory sections)\n")
    lines.append(
        "Discovered while recomputing the Class-2 families for `80_audit.py`; reported here in full, "
        "not folded into a silent pass, per the SIRIS cost & rigor protocol (\"report drift, don't "
        "absorb it\").\n"
    )
    lines.append("### Works per lab -- widespread, disproportionate growth\n")
    v2_by_lab = labs_wide.set_index("Structure name")["Pubs total"]
    v1_by_lab = labs_v1.set_index("Structure name")["Pubs total"]
    common_labs = (
        set(v1_by_lab.index) & set(v2_by_lab.index)
        - {"NO LAB", "ISITE"}
    )
    curated_v1_types = set(labs_v1.set_index("Structure name")["Structure type"])
    rows = []
    for name in sorted(common_labs):
        a, b = v1_by_lab[name], v2_by_lab[name]
        if a == 0:
            continue
        rows.append((name, int(a), int(b), (b - a) / a))
    drift = pd.DataFrame(rows, columns=["lab", "v1", "v2", "rel"])
    breaching = drift[drift["rel"].abs() > 0.30]
    lab_sum_v1 = int(labs_v1[labs_v1["Structure type"] == "lab"]["Pubs total"].sum())
    lab_sum_v2 = int(labs_wide[labs_wide["Structure type"] == "lab"]["Pubs total"].sum())
    lines.append(
        f"Comparing every structure name common to v1's and v2's deployed `ul_labs.parquet` "
        f"(excluding `NO LAB` and the removed `ISITE` pseudo-row, see (h)): "
        f"**{len(breaching)} of {len(drift)} structures** move by more than the `80_audit.py` "
        f"works_per_lab band (+-15% expected / >30% investigate), in BOTH directions -- e.g. `MSH` "
        f"{int(v1_by_lab['MSH'])} -> {int(v2_by_lab['MSH'])} "
        f"({signed_pct((v2_by_lab['MSH'] - v1_by_lab['MSH']) / v1_by_lab['MSH'])}), `ZAM` "
        f"{int(v1_by_lab['ZAM'])} -> {int(v2_by_lab['ZAM'])} "
        f"({signed_pct((v2_by_lab['ZAM'] - v1_by_lab['ZAM']) / v1_by_lab['ZAM'])}) on the low side, "
        f"through `IGEPCV` {int(v1_by_lab['IGEPCV'])} -> {int(v2_by_lab['IGEPCV'])} "
        f"(+{int(v2_by_lab['IGEPCV'] - v1_by_lab['IGEPCV'])} works) and `Georgia Tech` "
        f"{int(v1_by_lab['Georgia Tech'])} -> {int(v2_by_lab['Georgia Tech'])} on the high side. "
        f"Summed over `Structure type == \"lab\"` rows only: v1 {lab_sum_v1:,} -> v2 {lab_sum_v2:,} "
        f"({signed_pct((lab_sum_v2 - lab_sum_v1) / lab_sum_v1)}), i.e. lab-level totals grew roughly "
        f"twice as fast as the corpus itself ({pct(corpus_delta)}).\n\n"
        "**Partial explanation, not a full one.** Several of the largest gainers (`ZAM`, `SAMA`, "
        "`Observatoire`, `LISEC`) are heavily conference-paper/book-chapter labs, consistent with "
        "(c)'s doc-type shift. Others (`IGEPCV`, a health-genetics lab, 100% articles; `Georgia "
        "Tech`, an international joint campus) show large *relative* growth with no doc-type-mix "
        "explanation at all -- their absolute year-by-year publication rate looks stable across "
        "2019-2023 in the v2 data, which rules out a real ramp-up in output. The two shrinking labs "
        "(`MSH`, `ZAM`) use the same frozen OpenAlex id in both pulls, so the id is not the cause "
        "either. Both v1 and v2 match labs the same way (`corpus_authorships.institution_id`/`ror` "
        "== the lab's own id, no lineage expansion) per `pipeline/40_build_works.py`, so the "
        "remaining candidate causes are OpenAlex's own affiliation-matching model improving between "
        "the two pull vintages (plausible, external, and not something SIRIS controls) and/or a "
        "difference in how v1's original pipeline built its lab table that this report cannot "
        "recover without Phase 1's original code path (frozen, out of this first pass's fence).\n\n"
        "**RESOLVED by the F2 forensic investigation** (`reports/lab_delta_investigation.md`, "
        "dispatched specifically to chase this finding down): a work-level, five-bucket decomposition "
        "of all 50 ROR-decomposable breaching structures found **no v2 bug** (a corpus-wide scan of "
        "all 35,416 (work, lab) attributions, zero violations). The dominant cause (>82% of the "
        "aggregate delta) is corpus composition -- works OpenAlex's own perimeter query returns today "
        "that it did not return at v1's ~2025 crawl time, more than half of them not conference "
        "papers, so D36 alone does not explain it. The second driver (~28%) is upstream, live-"
        "verified: OpenAlex's affiliation-matching pipeline continues to re-process the historical "
        "record for years after an institution record is created, re-tagging old papers toward (and "
        "occasionally away from) a sub-institution's id -- the same mechanism explains both the "
        "gainers and the two losers, `MSH`/`ZAM`. A third, small contributor (+2.7%) is v1's own "
        "topic-null exclusion bug, disclosed above as section (j). On this evidence, the orchestrator "
        "signed `works_per_lab` off as a second pre-registered `EXPLAINED_EXCEPTION` in "
        "`80_audit.py` (2026-08-11, pending Nate ratification at review) -- the band itself was not "
        "widened; only the status of this specific, fully-decomposed breach was upgraded. See "
        "`reports/audit_run.md` for the current audit verdict.\n"
    )

    text = "\n".join(lines) + "\n"

    missing_sections = [s for s in REQUIRED_SECTIONS if s not in text]
    assert not missing_sections, f"shift report is missing mandatory section(s): {missing_sections}"

    out = ROOT / CONFIG["paths"]["reports"] / "shift_v1_v2_data.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")

    print(f"wrote {out} ({len(text):,} chars)")
    print(f"self-check: all {len(REQUIRED_SECTIONS)} mandatory sections present")
    print("PPtop section: present (a)")
    print("authorship truncation section: present (b)")


if __name__ == "__main__":
    main()
